### ISSUE TITLE
Unable to run on Ubuntu 16.04.2 

### ISSUE THREAD

**Issue by dave7280** [CapacitorSet/box-js#46] opened 2017-10-11 09:31 UTC
main@dev:~$ box-js test.js    
/usr/local/lib/node_modules/box-js/_run.js:49
let timeout = argv.timeout;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

Any solution?

**Comment by CapacitorSet** [comment] 2017-10-11 09:33
What version of node are you running (node --version)? box-js supports Node 6.0 and newer, mostly because it relies on Proxy that is an ES6 feature.

On October 11, 2017 11:31:10 AM GMT+02:00, dave7280 <notifications@github.com> wrote:
>main@dev:~$ box-js test.js    
>/usr/local/lib/node_modules/box-js/_run.js:49
>let timeout = argv.timeout;
>^^^
>
>SyntaxError: Block-scoped declarations (let, const, function, class)
>not yet supported outside strict mode
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/CapacitorSet/box-js/issues/46

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dave7280** [comment] 2017-10-11 09:36
Phhh.. v4 :) I will upgrade, i have absolutetly no experience with JS so i had to make this issue. Will let you know whether upgrading solved the problem.

**Comment by CapacitorSet** [comment] 2017-10-11 09:37
No problem! That's kind of a bug anyway, since it should have been caught in run.js (which I guess only catches 0.12 and previous versions). I'll fix that when I get home.

On October 11, 2017 11:36:07 AM GMT+02:00, dave7280 <notifications@github.com> wrote:
>Phhh.. v4 :) I will upgrade, i have absolutetly no experience with JS
>so i had to make this issue. Will let you know whether upgrading solved
>the problem.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/CapacitorSet/box-js/issues/46#issuecomment-335753728

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dave7280** [comment] 2017-10-11 09:47
I tried to analyze sample of js code, which i suppose has some anti debugging capabilities by exhausting the heap. Chrome hangs on it while being analyzed, firefox does timeout and ofc your solution does timeout as well. It's might be good benchmark of your sandbox...

This code is used by "Incapsula" CDN provider.

Might be good to benchmark your solution.

https://pastebin.com/fY4ZCQ4M

**Comment by CapacitorSet** [comment] 2017-10-11 10:22
Can't reproduce this, it doesn't crash on my Firefox (FF Nightly 58.0a1 on Arch), nor natively on Node, nor on box-js. However, on box-js it prints an error ("can't read property match of undefined"). On the other platforms it works correctly, printing some code to the console ([here](https://gist.github.com/CapacitorSet/7dc1ef924f3f031ce2355bd97bbd35ca)).

**Comment by CapacitorSet** [comment] 2017-10-11 10:29
I moved the "Can't read property match of undefined" to #47.

**Comment by CapacitorSet** [comment] 2017-10-11 10:56
I fixed #147 and pushed a patch (1.9.7). Not sure why it crashes on your device, but it doesn't seem to be a problem in box-js, seeing that I can run the analysis just fine - maybe you're low on memory?. Out of curiosity, try running the file directly in Node.

Closing this for now.

**Closed by CapacitorSet** 2017-10-11 10:56 UTC
