### ISSUE TITLE
Wsf file correct handling

### ISSUE THREAD

**Issue by Nwinternights** [CapacitorSet/box-js#23] opened 2017-07-05 18:43 UTC
Hi,
analyze.js handles wsf file which is <job><script>..</script><script>..</script></job>.
Some wsf have <job><script language=JScript>.......</script></job> .
Of course if I add the right tags box.js runs smoothy.
below a sample I submitted:
 (https://malwr.com/analysis/Yjc0MmFkY2JiNjIwNDMxMmE2YmJmZGIzNzU1MGVhZGU/)
before:
node run.js ../sample/wsf/00.wsf --debug
Using a 10 seconds timeout, pass --timeout to specify another timeout in seconds
Analyzing ../sample/wsf/00.wsf
Using detected encoding
The file seems to be encoded with ascii.

After tag modification:

node run.js ../sample/wsf/00.wsf   --download --no-shell-error
Using a 10 seconds timeout, pass --timeout to specify another timeout in seconds
Analyzing ../sample/wsf/00.wsf
Using detected encoding
The file seems to be encoded with ascii.
New ActiveXObject: Msxml2.XMLHTTP
GET http://actual-clinic.ru/counter/?rRP-8RCu_V6K4KpmizObebi7BQzTwk79mvZzsY-T-tBYheL-okeQKIl0pHkFCOJKdORQ_ffv9tYJ3iBR7UNBPQKY5i1vHS481
Downloading...
Downloaded 377344 bytes.
New ActiveXObject: Msxml2.XMLHTTP
GET http://pvo-taganrog.ru/counter/?rRP-8RCu_V6K4KpmizObebi7BQzTwk79mvZzsY-T-tBYheL-okeQKIl0pHkFCOJKdORQ_ffv9tYJ3iBR7UNBPQKY5i1vHS481
Downloading...
An error occurred while emulating a GET request to http://pvo-taganrog.ru/counter/?rRP-8RCu_V6K4KpmizObebi7BQzTwk79mvZzsY-T-tBYheL-okeQKIl0pHkFCOJKdORQ_ffv9tYJ3iBR7UNBPQKY5i1vHS481.
{ Error: getaddrinfo ENOTFOUND pvo-taganrog.ru pvo-taganrog.ru:80
    at doRequestWith (/home/socadmin/boxjs/node_modules/sync-request/index.js:87:17)
    at doRequest (/home/socadmin/boxjs/node_modules/sync-request/index.js:20:10)
    at Object.fetchUrl (/home/socadmin/boxjs/controller.js:53:17)
    at Proxy.XMLHTTP.send (/home/socadmin/boxjs/emulator/XMLHTTP.js:24:26)
    at Object.apply (/home/socadmin/boxjs/node_modules/vm2/lib/contextify.js:288:34)
    at vm.js:20:15
    at ContextifyScript.Script.runInContext (vm.js:53:29)
    at VM.run (/home/socadmin/boxjs/node_modules/vm2/lib/main.js:207:72)
    at Object.<anonymous> (/home/socadmin/boxjs/analyze.js:294:4)
    at Module._compile (module.js:569:30) code: 'ENOTFOUND' }
PS ok the URL was not reachable :-)

best regards

**Comment by CapacitorSet** [comment] 2017-07-05 22:34
This is a known issue, I'll have to implement decent XML parsing sometime.

Closing as a duplicate of #12.

**Closed by CapacitorSet** 2017-07-05 22:34 UTC

**Comment by CapacitorSet** [comment] 2017-07-05 22:48
I pushed b181403 which should strip all reasonable WSF tags. Can you try now?
